### ISSUE TITLE
QR code from relay on myNode won't scan on Android

### ISSUE THREAD

**Issue by theotherparker** [stakwork/sphinx-relay#153]
I got a Sphinx relay set up on myNode, but now the QR code won't scan. I tried restarting the relay, but no luck.

**Comment by pitoi** [comment]
If you are running tor & android, you'll need orbot (sometimes a restart of orbot is needed). Pinging @gonzaloaune

**Comment by theotherparker** [comment]
No tor, just a VPN. I am also running Graphene OS (on a Pixel 4XL), which doesn't have a QR code embedded in the camera app. Maybe that is a contributor?

**Comment by pitoi** [comment]
Graphene is the issue, we haven't tested the app on that OS yet. We'll need to remove some dependencies before it will work.

**Comment by theotherparker** [comment]
Alright, well happy to help test whenever y'all get around to testing!
