### ISSUE TITLE
Build pipeline on Drone.io for master branch

### ISSUE THREAD

**Issue by daniel-ro** [stakwork/sphinx-relay#16]
Create pipeline with [Drone.io](https://drone.io) to run tests, build image and push to a container registry.
First step for master branch, then for the rest of the branches

**Comment by Evanfeenstra** [comment]
This will be amazing! There is a feature/docker branch that wraps this repo up with LND in neutrino mode. might be a good place to start (I actually haven't tried it yet, but I will tomorrow first thing)

**Comment by kevkevinpal** [comment]
looks like we do all of this now :) maybe not with drone but we have automated testing and are pushing new docker images when we build a new release
