### ISSUE TITLE
Home node relay healthcheck

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-relay#160]
Before displaying the QR code, we should add some checks so we can make sure LND is ready:
 - channel open and active
 - we can provide URI options for routing hubs from and endpoint on Hub (@gonzaloaune )
 - fees on channel set to base = 0
 - remote balance needs to be more than 1% of channel balance to allow for inbound msgs / key exchange
 
Separate note: we need to make the payment payload dynamic based on the actual route fee or we need to regularly update the channel fees on our routing hubs to home nodes or msgs might fail due to the routing fee > payment.

A note in relay or in the home node interface, we need to let Android users know they need orbot with VPN on before they try to connect.

**Comment by jaydevstack** [comment]
@pitoi you saved my day, I wondered why the heck my app was not connecting to my relay / umbrel

> "we need to let Android users know they need orbot with VPN on before they try to connect"

Orbot was the key, thanks man

**Comment by pitoi** [comment]
Nice! the new version in kotlin will have native support.
