### ISSUE TITLE
Macaroon locations

### ISSUE THREAD

**Issue by dennisreimann** [stakwork/sphinx-relay#177]
I'm currently integrating Sphinx Relay into the BTCPay Server Docker deployment (see btcpayserver/btcpayserver-docker#458). 

Working on that I noticed that all macaroon are expected to be located in the same folder as the admin.macaroon ([reference](https://github.com/stakwork/sphinx-relay/blob/master/src/utils/macaroon.ts#L8)). This isn't the case for us and we'd like to keep deployed macaroons where they are for backwards compatibility. (LND introduced additional macaroons and moved the files after BTCPay started supporting LND)

Would you accept a PR that introduces optional config (via environment variables and the config json) for the individual macaroon paths? In addition to the existing [`macaroon_location`](https://github.com/stakwork/sphinx-relay/blob/master/src/utils/config.ts#L17) I'd add this then:

```js
router_macaroon_location: ENV.ROUTER_MACAROON_LOCATION || config.router_macaroon_location,
signer_macaroon_location: ENV.SIGNER_MACAROON_LOCATION || config.signer_macaroon_location,
```

**Comment by rockstardev** [comment]
Yeah, macaroons are not necessarily bunched in the same folder - if you want to support legacy LND installations this needs to be added.

**Comment by Evanfeenstra** [comment]
Yes @dennisreimann feel free to do a PR for that
