### ISSUE TITLE
MESSAGE SENT outside SW! { payment_error: ''

### ISSUE THREAD

**Issue by darrenahunter** [stakwork/sphinx-relay#18]
hi - am receiving this error in the terminal - not sure why. Msg was from Stefan and it  shows in the App as blank

=> [meme] authed!
2020-04-23 17:50:15
-> 2020-04-24 17:40:17: GET /messages?date=2020-04-23%2017:50:15 200 45ms
-> 2020-04-24 17:40:21: GET /balance 200 15ms
2020-04-25 08:40:17
-> 2020-04-24 17:40:28: GET /messages?date=2020-04-25%2008:40:17 200 41ms
=> exchangeKeys called { body: {}, params: { id: '4' }, query: {} }
-> 2020-04-24 17:40:29: POST /contacts/4/keys 200 32ms
MESSAGE SENT outside SW! { payment_error: '',
  payment_preimage:
   <Buffer f1 46 8e 28 bc 99 7e b1 ae 5d 94 09 c1 e5 2e 8a 91 40 86 b5 9d 0c 79 5f 59 8f d7 db f7 54 dc 2d>,
  payment_route:
   { total_time_lock: 627586,
     total_fees: '0',
     total_amt: '3',
     hops: [ [Object], [Object], [Object] ],
     total_fees_msat: '0',
     total_amt_msat: '3000' },
  payment_hash:
   <Buffer 9d 35 8e 7c 5c 77 c8 cf 4e ea 43 33 85 3a 94 9a a1 b6 70 02 84 3f e7 dd 69 48 79 cc f6 a8 9b 9e> }
=> confirm contact key { payload:
   { type: 11,
     sender:
      { contact_key:
         'MIIBCgKCAQEAzTLq4zJX+23xWZ9gfiqaTlLwR7T47sAWWvS38ZgMf+stlItywuwRbv/50pE6sjXz4jUypN61eSeGdbF83DXn3dXpORSdy8i1YoOhOXsUns6HmlL/eJUBfUNdpLyv1jHnAu/vOLSgT+UB18V3TBFr2o3uxEaXZ49dC4zULO9WkrR2/nNettDn0qg3++02nI7GCgRoF06FKPZ3roA8yrUWLnv3qwhPxJS1HLFgtsJWgttXgMq/+30Q3xK4+s899axspvNGyHSRmtChdkIu6/+M5NP60MPq1jLAsUgyx7ML6fgpAQip13Y+Og1RuPxAv8yUSJNVcC3ENQ1zazrfzulAgwIDAQAB',
        alias: 'cpunk',
        pub_key:
         '03b6e55ae20dc6b7fe3e9a42894da384f98a550f9a184a299809e010eb6fb0aa87' } } }
-> 2020-04-24 17:41:10: GET /balance 200 13ms
2020-04-25 08:40:28
-> 2020-04-24 17:41:12: GET /messages?date=2020-04-25%2008:40:28 200 53ms
-> 2020-04-24 17:42:11: GET /balance 200 14ms
-> 2020-04-24 17:44:23: GET /contacts 200 42ms
-> 2020-04-24 17:44:27: GET /contacts 200 23ms
-> 2020-04-24 17:44:39: GET /contacts 200 26ms

**Comment by Evanfeenstra** [comment]
fixed in latest master
