### ISSUE TITLE
How to install a builtin bot?

### ISSUE THREAD

**Issue by jimbojw** [stakwork/sphinx-relay#197]
sphinx-relay comes with several builtin bots (see [src/builtin](https://github.com/stakwork/sphinx-relay/tree/master/src/builtin)), including the `MotherBot` which can be used to install other bots.

Using the sphinx-relay API, how does one install/activate one of these bots, particularly `MotherBot`? To which route does one POST and what should be the payload?

**Comment by Evanfeenstra** [comment]
mother bot is installed always. You just type "/bot help" in a tribe that you own

**Comment by jimbojw** [comment]
I'm running my own sphinx-relay, I created a tribe (unlisted). `/bot help` (or `/bot anything`) returns no results.

Making an authenticated GET request to the `/bots` route returns an empty JSON array `[]`.

**Comment by jimbojw** [comment]
Never mind. It's now working. Unclear why it wasn't responding before.
