### ISSUE TITLE
Update to Wiki Page for Home Node

### ISSUE THREAD

**Issue by shakneymons** [stakwork/sphinx-relay#208]
Hi Sphinx! Have recently updated my Sphinx Chat App on Android today. Found out that the Kotlin version of the App no longer requires Orbot as Tor is supported natively. Suggest an update to wiki page section for [apps](https://github.com/stakwork/sphinx-relay/wiki/Home-node-FAQ#apps) as the current version of Sphinx on Android no longer requires it.

Great work with the app so far!

**Comment by pitoi** [comment]
thanks, we'll get it taken care of
