### ISSUE TITLE
Installing relay error

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-relay#21]
User getting an error trying to add relay to a btcpayserver install.

root@btcpay:/var/lib/docker/volumes/sphinx-relay# npm run prod

> nodeapp@1.0.0 prod /var/lib/docker/volumes/sphinx-relay
> cp config/app.json dist/config/app.json && cp config/config.json dist/config/config.json && env NODE_ENV=production node dist/app.js

env: ‘node’: No such file or directory

**Comment by Evanfeenstra** [comment]
just need to install node

**Comment by kevkevinpal** [comment]
this is stale and likely the solution above resolved issue closing
