### ISSUE TITLE
Relay invite error on home node

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-relay#22]
Javier's node: Ubuntu lnd 0,9, Nginx fwd 80->3001

-> 2020-04-28 23:06:56: GET /signer/st1meD4ZPQtvDQVkkdR0y4xf2jjrmENees_l0hPxCsM= 200 5ms
-> 2020-04-28 23:07:00: GET /socket 401 0ms
-> 2020-04-29 00:53:28: GET / 404 875ms
[hub error] { FetchError: invalid json response body at https://hub.sphinx.chat/api/v1/invites/check reason: Unexpected token < in JSON at position 0
    at /home/ubuntu/sphinx-relay/node_modules/node-fetch/lib/index.js:272:32
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
  message:
   'invalid json response body at https://hub.sphinx.chat/api/v1/invites/check reason: Unexpected token < in JSON at position 0',
  type: 'invalid-json' }

**Comment by Evanfeenstra** [comment]
Maybe hub was being rebooted or something...

**Comment by Evanfeenstra** [comment]
Yes, this pops up when hub is rebooted, does not cause any crash
