### ISSUE TITLE
Ability to block a contact

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-relay#224]
- Add a boolean column on Contact table (blocked) and include it in the contact json serializer

- Add a new endpoint on relay that allows to block/unblock a contact: 
      1. Receives ContactId
      2. Returns Contact object

- Contact should still be returned in getContacts endpoints
- Avoid push notification for messages coming from blocked contacts in private conversations

**Comment by mattbajorek** [comment]
@Evanfeenstra was this already handled in https://github.com/stakwork/sphinx-relay/pull/225?

**Comment by middlew4y** [comment]
> @Evanfeenstra was this already handled in #225?

yup!

**Comment by Evanfeenstra** [comment]
> @Evanfeenstra was this already handled in #225?

yes
