### ISSUE TITLE
Not sure how to contribute to project

### ISSUE THREAD

**Issue by 1nF0rmed** [stakwork/sphinx-relay#229]
Hello,
I would like to contribute to the development of the project but am not sure where to begin as I couldn't find any `good-first-issue`.
Is there a developer slack, discord or any other communications channel that I can join to understand what I could contribute to?
Thank you!

**Comment by kevkevinpal** [comment]
Hey @1nF0rmed glad to hear that you want to help out with the project. 

If you're a dev I would recommend getting https://github.com/stakwork/sphinx-stack running as this will be the dev environment we'll be working on. 

If you're a tester I would recommend joining the sphinx android testers tribe
https://tribes.sphinx.chat/t/sphinxandroidtesters

**Comment by kevkevinpal** [comment]
Closing for now but we do occasionally post bounties on the sphinx-stack repo and any documentation would be a `good-first-issue` I can open up some documentation tasks if that would be of interest to you
