### ISSUE TITLE
Wiki: BTC to sats conversion is wrong 

### ISSUE THREAD

**Issue by thesimplekid** [stakwork/sphinx-relay#231]
https://github.com/stakwork/sphinx-relay/wiki/Home-node-FAQ#is-your-node-ready

"You have to have some bitcoin (recommend at least .01 or 100,000 satoshis)"

.01 btc does not equal 100,000 sats it 1,000,000

should be either .001

I would submit a PR but don't think i cant on wikis

**Comment by Evanfeenstra** [comment]
haha thanks for seeing that! its updated
