### ISSUE TITLE
Feed content type

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-relay#235]
We need to add a feed content type field on `chat` to support `listen / watch / read` types and any other type we might want to support in the future. 
- Field could be an `INT enum` so we might need a references table
- Add param `feed_type` on `POST /group`
- Add param `feed_type` on `PUT /group/id`
- Add field on chat model and table so it's stored there
- Add param on call to tribes server so it's created there as well 

This way user can set a podcast RSS feed url on Feed Url field, or other types of RSS feed (youtube, newsletters, etc).

Examples: 
Video: https://www.youtube.com/feeds/videos.xml?channel_id=UCnCikd0s4i9KoDtaHPlK-JA
Newsletter: https://thesequence.substack.com/feed / https://medium.com/feed/@jjpryor

**Comment by mattbajorek** [comment]
@Evanfeenstra was this already handled in https://github.com/stakwork/sphinx-relay/commit/f101694aac3ac9388eea81f3f7ac413f134f9a59?

**Comment by Evanfeenstra** [comment]
> @Evanfeenstra was this already handled in [f101694](https://github.com/stakwork/sphinx-relay/commit/f101694aac3ac9388eea81f3f7ac413f134f9a59)?

yes, thanks @mattbajorek
