### ISSUE TITLE
Unable to run controller tests

### ISSUE THREAD

**Issue by mattbajorek** [stakwork/sphinx-relay#241]
sphinx-relay git:(master) ✗ npx ava src/tests/controllers/tribe.test.ts --verbose --serial --timeout=2m

  ✖ tribe Rejected promise returned by test
  ─

  tribe

  Rejected promise returned by test. Reason:

  StatusCodeError {
    error: 'Invalid credentials',
    message: '401 - Invalid credentials',
    name: 'StatusCodeError',
    options: {
      body: {
        app_url: '',
        description: 'A testing tribe',
        escrow_amount: 0,
        escrow_millis: 0,
        feed_type: 0,
        feed_url: '',
        img: '',
        is_tribe: true,
        name: 'Test Tribe: alice',
        price_per_message: 0,
        price_to_join: 0,
        private: false,
        tags: [],
        unlisted: true,
      },
      callback: undefined,
      headers: {
        'x-user-token': 'XICKa9DFzbC9n6uh/zDo',
      },
      json: true,
      method: 'POST',
      resolveWithFullResponse: false,
      simple: true,
      transform: undefined,
      uri: 'http://host.docker.internal:3001/group',
    },
    response: IncomingMessage {
      _consuming: false,
      _dumped: false,
      _events: {
        close: Array [ … ],
        data: Function {},
        end: Array [ … ],
        error: Function {},
      },
      _eventsCount: 4,
      _maxListeners: undefined,
      _readableState: ReadableState [
        autoDestroy: true,
        awaitDrainWriters: null,
        buffer: BufferList [ … ],
        closeEmitted: true,
        closed: true,
        constructed: true,
        dataEmitted: true,
        decoder: null,
        defaultEncoding: 'utf8',
        destroyed: true,
        emitClose: true,
        emittedReadable: false,
        encoding: null,
        endEmitted: true,
        ended: true,
        errorEmitted: false,
        errored: null,
        flowing: true,
        highWaterMark: 16384,
        length: 0,
        multiAwaitDrain: false,
        needReadable: false,
        objectMode: false,
        pipes: [],
        readableListening: false,
        reading: false,
        readingMore: true,
        resumeScheduled: false,
        sync: true,
        [Symbol(kPaused)]: false,
      ],
      aborted: false,
      body: 'Invalid credentials',
      caseless: Caseless {
        dict: Object { … },
      },
      client: Socket {
        _events: Object { … },
        _eventsCount: 7,
        _hadError: false,
        _host: 'host.docker.internal',
        _httpMessage: ClientRequest { … },
        _maxListeners: undefined,
        _parent: null,
        _pendingData: null,
        _pendingEncoding: '',
        _readableState: ReadableState [ … ],
        _server: null,
        _sockname: null,
        _writableState: WritableState [ … ],
        allowHalfOpen: false,
        connecting: false,
        parser: null,
        server: null,
        [Symbol(async_id_symbol)]: 16,
        [Symbol(kHandle)]: TCP { … },
        [Symbol(kSetNoDelay)]: false,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBuffer)]: null,
        [Symbol(kBufferCb)]: null,
        [Symbol(kBufferGen)]: null,
        [Symbol(kCapture)]: false,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(RequestTimeout)]: undefined,
      },
      complete: true,
      httpVersion: '1.1',
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      method: null,
      rawHeaders: [
        'X-DNS-Prefetch-Control',
        'off',
        'X-Frame-Options',
        'SAMEORIGIN',
        'Strict-Transport-Security',
        'max-age=15552000; includeSubDomains',
        'X-Download-Options',
        'noopen',
        'X-Content-Type-Options',
        'nosniff',
        'X-XSS-Protection',
        '1; mode=block',
        'Access-Control-Allow-Origin',
        '*',
        'Content-Type',
        'text/plain',
        'Date',
        'Sat, 30 Oct 2021 23:23:27 GMT',
        'Connection',
        'close',
        'Transfer-Encoding',
        'chunked',
      ],
      rawTrailers: [],
      req: ClientRequest {
        _closed: false,
        _contentLength: null,
        _defaultKeepAlive: true,
        _ended: true,
        _events: Object { … },
        _eventsCount: 5,
        _hasBody: true,
        _header: `POST /group HTTP/1.1␍␊
        x-user-token: XICKa9DFzbC9n6uh/zDo␍␊
        host: host.docker.internal:3001␍␊
        accept: application/json␍␊
        content-type: application/json␍␊
        content-length: 244␍␊
        Connection: close␍␊
        ␍␊
        `,
        _headerSent: true,
        _keepAliveTimeout: 0,
        _last: true,
        _maxListeners: undefined,
        _onPendingData: Function nop {},
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _trailer: '',
        aborted: false,
        agent: Agent { … },
        chunkedEncoding: false,
        destroyed: false,
        finished: true,
        host: 'host.docker.internal',
        insecureHTTPParser: undefined,
        maxHeaderSize: undefined,
        maxHeadersCount: null,
        maxRequestsOnConnectionReached: false,
        method: 'POST',
        outputData: [],
        outputSize: 0,
        parser: null,
        path: '/group',
        protocol: 'http:',
        res: [Circular],
        reusedSocket: false,
        sendDate: false,
        shouldKeepAlive: false,
        socket: Socket { … },
        socketPath: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        useChunkedEncodingByDefault: true,
        writable: true,
        [Symbol(kCapture)]: false,
        [Symbol(kNeedDrain)]: false,
        [Symbol(corked)]: 0,
        [Symbol(kOutHeaders)]: Object { … },
      },
      request: Request {
        __isRequestRequest: true,
        _auth: Auth { … },
        _callback: Function RP$callback {},
        _callbackCalled: true,
        _destdata: true,
        _disableCookies: true,
        _ended: true,
        _events: Object { … },
        _eventsCount: 5,
        _jar: undefined,
        _json: true,
        _maxListeners: undefined,
        _multipart: Multipart { … },
        _oauth: OAuth { … },
        _qs: Querystring { … },
        _redirect: Redirect { … },
        _rp_callbackOrig: undefined,
        _rp_options: Object { … },
        _rp_promise: Promise { … },
        _rp_reject: Function {},
        _rp_resolve: Function {},
        _started: true,
        _tunnel: Tunnel { … },
        agent: Agent { … },
        agentClass: Function Agent { … },
        body: '{"name":"Test Tribe: alice","description":"A testing tribe","tags":[],"is_tribe":true,"price_per_message":0,"price_to_join":0,"escrow_amount":0,"escrow_millis":0,"img":"","unlisted":true,"private":false,"app_url":"","feed_url":"","feed_type":0}',
        callback: Function {},
        dests: [],
        explicitMethod: true,
        getHeader: Function {},
        hasHeader: Function {},
        headers: Object { … },
        host: 'host.docker.internal',
        href: 'http://host.docker.internal:3001/group',
        httpModule: Object { … },
        localAddress: undefined,
        method: 'post',
        ntick: true,
        originalCookieHeader: undefined,
        originalHost: 'host.docker.internal:3001',
        originalHostHeaderName: 'host',
        path: '/group',
        pool: {},
        port: '3001',
        proxy: null,
        readable: true,
        removeHeader: Function {},
        req: ClientRequest { … },
        response: [Circular],
        responseContent: [Circular],
        setHeader: Function {},
        setHost: true,
        tunnel: false,
        uri: Url { … },
        writable: true,
        [Symbol(kCapture)]: false,
      },
      socket: Socket {
        _events: Object { … },
        _eventsCount: 7,
        _hadError: false,
        _host: 'host.docker.internal',
        _httpMessage: ClientRequest { … },
        _maxListeners: undefined,
        _parent: null,
        _pendingData: null,
        _pendingEncoding: '',
        _readableState: ReadableState [ … ],
        _server: null,
        _sockname: null,
        _writableState: WritableState [ … ],
        allowHalfOpen: false,
        connecting: false,
        parser: null,
        server: null,
        [Symbol(async_id_symbol)]: 16,
        [Symbol(kHandle)]: TCP { … },
        [Symbol(kSetNoDelay)]: false,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBuffer)]: null,
        [Symbol(kBufferCb)]: null,
        [Symbol(kBufferGen)]: null,
        [Symbol(kCapture)]: false,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(RequestTimeout)]: undefined,
      },
      statusCode: 401,
      statusMessage: 'Access invalid for user',
      toJSON: Function responseToJSON {},
      upgrade: false,
      url: '',
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: {
        'access-control-allow-origin': '*',
        connection: 'close',
        'content-type': 'text/plain',
        date: 'Sat, 30 Oct 2021 23:23:27 GMT',
        'strict-transport-security': 'max-age=15552000; includeSubDomains',
        'transfer-encoding': 'chunked',
        'x-content-type-options': 'nosniff',
        'x-dns-prefetch-control': 'off',
        'x-download-options': 'noopen',
        'x-frame-options': 'SAMEORIGIN',
        'x-xss-protection': '1; mode=block',
      },
      [Symbol(kHeadersCount)]: 22,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0,
      [Symbol(RequestTimeout)]: undefined,
    },
    statusCode: 401,
  }

  › new StatusCodeError (node_modules/ava-http/node_modules/request-promise/lib/errors.js:26:15)
  › Request.RP$callback [as _callback] (node_modules/ava-http/node_modules/request-promise/lib/rp.js:68:32)
  › Request.self.callback (node_modules/request/request.js:185:22)
  › Request.<anonymous> (node_modules/request/request.js:1154:10)
  › IncomingMessage.<anonymous> (node_modules/request/request.js:1076:12)

  ─

  1 test failed

**Comment by kevkevinpal** [comment]
@mattbajorek would you be able to try checking out this branch https://github.com/kevkevinpal/sphinx-relay/tree/kp/boost

you can do so by running
`git fetch origin pull/240/head:PR240`
`git checkout PR240`

then try running this again
`npx ava src/tests/controllers/tribe.test.ts --verbose --serial --timeout=2m`

then let me know what the output is.

Also was this the only test file you were having issues with because I was having difficulties with this one but in this PR I was able to make it work on my end, only I was having a timeout issue rather than a 401 denied but maybe these changes may help with you as well

In addition, would you also be able to check to see if when you run `docker-compose up -d` that both `sphinx-stack_lndsetup_1` and `sphinx-stack_relaysetup_1` have exited since this will indicate that the setup of the containers are complete,  you can check this by running `docker-compose ps` in the sphinx-stack repo

**Comment by kevkevinpal** [comment]
I think I just came across the same error just now, I think this maybe happening when the node.json file in `src/tests/configs/nodes.json` in sphinx-relay is mismatched with he one in `./relay/NODES.json` in sphinx-stack

**Comment by mattbajorek** [comment]
@kevkevinpal Thanks for the assistance! I read the code wrong thinking `./config/nodes.json` was `src/configs/nodes.json` instead of `src/tests/config/nodes.json`.
