### ISSUE TITLE
prevent replay attacks, secure x-user-token

### ISSUE THREAD

**Issue by Evanfeenstra** [stakwork/sphinx-relay#269]
- relay serves a "transport_pubkey" which is a public key that can be used to encrypt x-user-token.
- app encrypts the x-user-token + timestamp for every request. Timestamp is UNIX time, 10 digits. Entire encrypted text is base64 encoded, and added to an HTTP header named `x-transport-token`
- app signs the entire request body for integrity
- relay stores every request for a specific amount of time (say one minute), so an encrypted x-user-token cannot be used twice
- relay checks the timestamp for each request is within the bounds (one minute)

**Comment by kevkevinpal** [comment]
@Evanfeenstra does this seem right, trying to see if I understand how it'll work

relay serve's `transport_pubkey` to client
`x-transport-token = base64(encrypt(transport_pubkey, x-user-token + timestamp))`
send request with `x-transport-token`
relay stores request for a minute

if another request comes to relay with the same `x-transport-token` ie decrypted with the same timestamp as previous request then reject the new request

also reject any requests with timestamps older than a minute

then we can also setup a cron job to clear where we are storing the requests

**Comment by Evanfeenstra** [comment]
Exactly.

**Comment by kevkevinpal** [comment]
Going to close this as it is complete on relay's end just need to update clients to use the x-transport-token

**Comment by Evanfeenstra** [comment]
- You can GET /request_transport_token to retrieve the relay transport token (returns object {transportToken:'...'}
- which is used to encrypt {userToken}|{timestamp}
- that encrypted token is put into the `x-transport-token` header

**Comment by Evanfeenstra** [comment]
@kevkevinpal looking at the ownerMiddleware, you are parsing the date like `new Date(splitTransportTokenTimestamp)`. And in the test you are just doing a Date.toString()... instead lets use unix timestamps as that is an easy standard across any client. You can always use the `moment` lib

**Comment by kevkevinpal** [comment]
once we merge this in we should be good to close this issue

https://github.com/stakwork/sphinx-kotlin/pull/436

**Comment by kevkevinpal** [comment]
https://github.com/stakwork/sphinx-kotlin/pull/436

**Comment by kevkevinpal** [comment]
closing this issue since it will be implemented on ios and mac soon and already merged in kotlin
