### ISSUE TITLE
Restore improvements

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-relay#271]
In order to improve the restore process and allow users to see progress and stop restore in the middle we need some changes on relay endpoints:

### THESE CHANGES SHOULD APPLY TO THE TWO MESSAGES ENDPOINT (`messages.ts`):
```
- getAllMessages
- getMsgs
```

### CHANGES

- Add `new_messages_total` key on response. This should return the total amount of messages (not the total on the current page, but the total count). That way the app can calculate the progress based on total and current page. 
- Change messages order from `['id', 'asc']` to `['id', 'desc']`. So we can implement a way to allow user to stop restore process in the middle. Right now the oldest messages are returned first, then if stopped newest messages won't be restored

**Comment by kevkevinpal** [comment]
@tomastiminskas let me know if this PR looks about what you were looking for, also will add some more checks for the test added in this PR

**Comment by kevkevinpal** [comment]
@tomastiminskas are we good to close this issue?

**Comment by tomastiminskas** [comment]
@kevkevinpal yes!
