### ISSUE TITLE
Lite node balance

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-relay#275]
During the setup the amount to send/receive is incorrect. It should display the max receive on 500k sats and max send of the default amount provided with that lite node (1-2000 sats)

**Comment by tomastiminskas** [comment]
@pitoi those values come directly from relay and are just shown on the app. I reported the same some time ago for virtual nodes (which I think it's your case), and Evan did a fix, but not sure if he finally pushed it to proxy server or not. 

But on any case it's a fix @Evanfeenstra or @kevkevinpal should do

**Comment by Evanfeenstra** [comment]
Yes this was fixed and proxy (both test and prod) are updated

https://github.com/stakwork/sphinx-relay/commit/8aadb27661e3b48db07b88a884f9b70d2d9c2290

**Comment by kevkevinpal** [comment]
looks like this was fixed closing this issue
