### ISSUE TITLE
pinned messages

### ISSUE THREAD

**Issue by Evanfeenstra** [stakwork/sphinx-relay#284]
Tribes and Relay DB have a new TEXT column `pin`, for pinning messages to tribes. It can edited just like all the other columns. It is a message `uuid`, that the apps can use to find the message and display it at the top of the tribe

**Comment by Evanfeenstra** [comment]
It can be included in "edit tribe" route like all other fields. 

But also there is another route for editing it: **PUT /chat_pin/:id** where "id" is the chat ID. The body is { pin:"" }

**Comment by kevkevinpal** [comment]
@Evanfeenstra do we look good to merge this change seems like we had a couple PR's just not implemented in the mobile app

https://github.com/stakwork/sphinx-relay/pull/283
https://github.com/stakwork/sphinx-relay/pull/290
