### ISSUE TITLE
Add a test for "unique" aliases

### ISSUE THREAD

**Issue by Evanfeenstra** [stakwork/sphinx-relay#292]
When a message comes through, the "alias" is checked against other ChatMembers. So like someone cannot copy the "alias" of the owner (or any other member). 

https://github.com/stakwork/sphinx-relay/blob/master/src/network/receive.ts#L214

This needs to be tested!

**Comment by kevkevinpal** [comment]
able to close since we merged this PR https://github.com/stakwork/sphinx-relay/pull/397
