### ISSUE TITLE
build fails on node.js v17 due to depreciated grpc

### ISSUE THREAD

**Issue by drrossum** [stakwork/sphinx-relay#295]
This is the upstream bug that is the culprit.  The proposed solution is to drop grpc for @grpc/grpc-js
https://github.com/grpc/grpc-node/issues/2001

**Comment by kevkevinpal** [comment]
@drrossum thanks for bringing this up we will continue to monitor the thread you posted to see if any changes are proposed to the grpc library instead of dropping for `grpc-js`

**Comment by drrossum** [comment]
That bug is over a year old and was practically closed as "wontfix" IIUC

**Comment by Evanfeenstra** [comment]
Ya its super annoying, i tried to switch out for @grpc/grpc-js a long time ago, but ever single field name changed from snake_case to camelCase... if there is any easy way to force snake_case then it would be an easy fix...

**Comment by kevkevinpal** [comment]
So oddly when I tried building this PR https://github.com/stakwork/sphinx-relay/pull/410 by editing the Dockerfile to `node:18-buster-slim` it worked but when I changed it to `node:17-buster-slim` it failed
