### ISSUE TITLE
New socket.io CORS

### ISSUE THREAD

**Issue by Evanfeenstra** [stakwork/sphinx-relay#343]
Getting "Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource" when connecting to new socket.io from win/linux desktop (which uses Electron so CORS is an issue)

@kevkevinpal

**Comment by kevkevinpal** [comment]
ok gotcha is that just an issue on the win/linux desktop? I think I know how to fix this issue but we'll need to test again on the other platforms aswell

**Comment by kevkevinpal** [comment]
Merged Change closing now
