### ISSUE TITLE
Stuck between "new user" and "existing user" unable to use the app - catch 22

### ISSUE THREAD

**Issue by lillyone** [stakwork/sphinx-relay#351]
Okay, I'm totally new to this so bare with me. I've managed to open up sphinx and send and receive a few messages on my Android phone. But then I was somehow jolted out of the app and now I can't get it up running again. When I open Sphinx I'm given the choice between "new user" or "existing user". When I click on "existing user" I'm being asked to copy my keys from my desktop app and paste it into the app on my phone. However when I try to open up Sphinx on my desktop I'm being presented with the exact same choice. Catch 22 indeed. I'm using my own Raspiblitz as connecting node. Would so much appreciate help in this matter. Please let me know what kind of information I can provide for greater clarification.

Thank you!

**Comment by kevkevinpal** [comment]
Hmm so it seems you're unable to get into the app at all?

You might need to uninstall and reinstall sphinx relay on the raspiblitz and generate a new invite code.

Keep in mind this will delete old chats.

But after you setup sphinx again be sure to backup your keys as that's the only way to get access back to your account if you accidentally delete your app

**Comment by lillyone** [comment]
Thank you so much for the reply.  The issue seems to be solved for now. I reinstalled a version of the app from github, so fingers crossed I hope it keeps on working moving forward...

**Comment by kevkevinpal** [comment]
> Thank you so much for the reply. The issue seems to be solved for now. I reinstalled a version of the app from github, so fingers crossed I hope it keeps on working moving forward...

ok sounds good if the issue starts occurring again feel free to reopen/comment on this issue

closing for now

**Comment by lillyone** [comment]
Yep now it happened again. The flash icon in the upper right corner has turned orange and when I press it the app says "disconnected node". Could it perhaps be an issue with the phone? The sphinx app works great on my laptop (mac).
