### ISSUE TITLE
Enabling AMP payments - $@1,000,000

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-relay#361]
`[Description]`
We want to enable AMP payments in addition to keysend messages with sphinx-relay

This is because right now if there is a node runner who wants to send a payment using sphinx but the payment is larger than the amount of funds they can send through a single channel the payment will fail.

With this change we need to allow both keysend and amp and we can do this in two ways, either first try a keysend and if it fails try an AMP payment or the otherway around

Some changes have been made as a start here --> https://github.com/stakwork/sphinx-relay/pull/353

But for some reason when trying to startup sphinx-stack with `--accept-amp` we still run into the error `destination doesn\'t support AMP payments`

Currently testing off of this branch in sphinx-stack 
https://github.com/stakwork/sphinx-stack/tree/lightingLabsLnd

-----

`[Complexity] (1,2,3,5,7)`

3

----

`[To Reproduce]`

Download the `sphinx-stack` and `sphinx-relay`

get the testing environment running for sphinx-stack

run 
`npx ava src/tests/controllers/ampMessage.test.ts --verbose --serial --timeout=2m`

it fails right now but we need to get it to pass

---

`[etc]`
If you're having troubles getting the env setup or are having other issue please checkout this doc
https://github.com/stakwork/sphinx-stack/blob/master/docs/developingOnSphinx.md
or join the developing on sphinx tribe
or throw a comment below for help

**Comment by Evanfeenstra** [comment]
I would say first try AMP, then keysend :)
