### ISSUE TITLE
Socket logs

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-relay#367]
@kevkevinpal  Could you please add some logs on the `socket.sendJson` method and deploy to Paul's node? We are checking into an issue and that would be helpful. We would need to print the socket message type and the date time.

**Comment by kevkevinpal** [comment]
ok cool just reset with logs just added one here in this branch

https://github.com/stakwork/sphinx-relay/tree/kp/sendJsonLogs

**Comment by kevkevinpal** [comment]
lemme know if you want me to add logs elsewhere and redeploy
