### ISSUE TITLE
setupTransportToken is never called

### ISSUE THREAD

**Issue by ProofOfKeags** [stakwork/sphinx-relay#368]
also having to set this up manually is not documented anywhere.

**Comment by Evanfeenstra** [comment]
it is all  automated right @kevkevinpal  ?

**Comment by ProofOfKeags** [comment]
what is automated?

**Comment by Evanfeenstra** [comment]
ah, sorry, you are right, that exact funcition is never called. However, the `requestTransportKey` does the same thing. If the transport tokens dont exist, they are created on the first time that they are actually requested

`setupTransportToken` should be deleted as its not used in fact

**Comment by kevkevinpal** [comment]
I see what he's saying @Evanfeenstra looks like we removed setupTransportToken from setup since we do the same thing when call the transportToken endpoint if its not generated yet
