### ISSUE TITLE
Umbrel transportToken not found error

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-relay#375]
After shutting down my umbrel node and then moving to a different network I encountered this error with the transport token, maybe we should catch and then generate the transport token if that part of the code fails?

<img width="1790" alt="Screen Shot 2022-05-24 at 9 27 19 AM" src="https://user-images.githubusercontent.com/15950706/170060181-f0250bd3-fdf7-4e60-a7b5-6563015220c7.png">

**Comment by Evanfeenstra** [comment]
oh i see, its from the socket connection! 

Ya i guess we should generate the keys if they dont already exist at that point
