### ISSUE TITLE
Wrong sender_pic on tribes

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-relay#381]
When joining a tribe and getting the messages history, the messages sent by a user who has no profile picture are showing with the admin picture and sender_pic.

**Comment by tomastiminskas** [comment]
Seems like the issue is not just affecting history but all tribe messages. When admin forwards a members's message to the rest of the members, if the sender of the message has not profile picture, then the admin will set his own as sender_pic on the message.

**Comment by kevkevinpal** [comment]
@tomastiminskas was this fixed I don't see this happening for users but I did see the admin profile pic on some bots
