### ISSUE TITLE
feature request/idea ticket bot

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-relay#389]
Start of a thread for a ticket or some sort of task bot that allows a user to quickly post a help wanted ad

**Comment by Bribrian2** [comment]
- when /ticket is posted can the bot delete it and post a cute message
- /bot install ticket
   - /ticket create <link> <desc> <amount> (optional <time limit>) 
   - /ticket complete <ID> <Username>
   - /ticket delete <ID>
   - /ticket modify <ID> <link> <desc> <amount>
   - /ticket assign <ID> <name> 
- Ticket need to cost money
- /ticket list
   - list of all IDs, URLs, descriptions, amount,
   - optional show all including the people that completed the task

**Comment by DitchRat** [comment]
im here

**Comment by kevkevinpal** [comment]
@DitchRat heres a link to the sphinx bot

https://github.com/stakwork/sphinx-bots

we'll have to use this to start creating a ticket bot

**Comment by kevkevinpal** [comment]
Also heres a sample bot that sends a test message

https://github.com/stakwork/sphinx-example-bot

**Comment by Bribrian2** [comment]
https://www.figma.com/file/EXaScU6t5vQOUKohwQrg2N/adding-a-bot-to-a-tribe?node-id=0%3A1

**Comment by kevkevinpal** [comment]
@DitchRat 
Good doc on how to get bots running on sphinx-stack

https://github.com/stakwork/sphinx-stack/blob/master/docs/bots.md

**Comment by kevkevinpal** [comment]
stale issue closing
