### ISSUE TITLE
Changes needed to upgrade to node v16

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-relay#403]
As sphinx-relay is right now we must build using node version 14 which may become an issue in the future and has already caused some issues so I'm creating this issue as a board of all the changes that are needed to fully support the latest node version

posted some issues below that are related feel free to link more

https://github.com/stakwork/sphinx-relay/issues/295
https://github.com/stakwork/sphinx-relay/issues/206

may not be node version related but worth putting here
https://github.com/stakwork/sphinx-relay/issues/130

**Comment by antonilol** [comment]
i run and code/test sphinx on node v16.16.0, i did try to use v17 first but grpc did not work there so downgraded to v16

**Comment by kevkevinpal** [comment]
> i run and code/test sphinx on node v16.16.0, i did try to use v17 first but grpc did not work there so downgraded to v16

hmm I tried changing in the docker file from `node:12-buster-slim` to `node:16-buster-slim` and it failed when building using 

`docker build -t sphinxlightning/sphinx-relay .`

**Comment by kevkevinpal** [comment]
Created this PR/branch on my fork will be trying to update to node v16 here https://github.com/kevkevinpal/sphinx-relay/pull/16

going to upgrade sqlite3 to version 5 and also update some types as after updating to sqlite3 v5 it wants us to be stricter with the typing

**Comment by kevkevinpal** [comment]
This is almost finished I've just about updated all of our clusters last I need to do is the proxy servers and our internal nodes that we use

**Comment by kevkevinpal** [comment]
I can close this now yay!!
