### ISSUE TITLE
Add icons for for Jitsi, Replit, and Loom on ticket cards $@50000

### ISSUE THREAD

**Issue by rkirkendall** [stakwork/sphinx-relay#434]
Related to additional ticket fields added in [this ticket](https://github.com/stakwork/sphinx-relay/issues/433)

Show icons on the ticket card to indicate the type of context available for the ticket. Icons should indicate the presence of Loom links, Jitsi links (in the case of a live help ticket), or Replit links.

Icons should replace the "visible" icon (since by seeing a ticket, you already know it's visible :)
![Screen Shot 2022-09-15 at 10 55 04 AM](https://user-images.githubusercontent.com/1122859/190476441-54755c2f-7c77-4694-b330-e2487e9272bc.png)

**Comment by kevkevinpal** [comment]
This is stale and new design approach is being taken closing for now
