### ISSUE TITLE
Payments back to content creators

### ISSUE THREAD

**Issue by soup20** [stakwork/sphinx-relay#436]
We want to pay content creators when their content is consumed in Second Brain.

When a user consumes a piece of content in second brain, we should look at the rss feed attached to that content to find the value block (a part of the rss feed containing payment destinations and percentages).

Once we have the value block, we can make payments (pay as you consume) using the same logic we use when paying creators for content consumed in the Sphinx feed (this is in relay).

**Comment by Evanfeenstra** [comment]
@soup20 @omoniyi24 

you can query podcast index feeds using the feed_url like this https://tribes.sphinx.chat/feed?url=http://mp3s.nashownotes.com/pc20rss.xml

It returns the RSS feed parsed as JSON, including the value block. If there is no value block, then one is "injected" into the JSON using the tribe admin's pubkey (if there is a tribe that has that feed url set)
