### ISSUE TITLE
Earnings distribution

### ISSUE THREAD

**Issue by soup20** [stakwork/sphinx-relay#437]
Goal: We want lightning node operators to be incentivized to host various graphs. We need to distribute the income to three parties: creators, taggers, graph hosters. 

Open question: do we pay creators directly when it can difficult to find out who the creator is? or do we just pay the tagger, which makes the creator have an incentive to help create the graph by submitting their work?

When a clip is boosted or played in Second Brain, the audio tagger who tagged the clip should receive that money.

For this to happen:
1. All audio taggers log in to Stakwork via Sphinx.
2. Update the Stakwork endpoint to accept their Sphinx pubkeys.
3. When an audio tagging episode is passed from Stakwork to neo4j, include the pubkey of the worker who tagged it.
4. Store pubkey as a property of each clip node.
5. When a user boosts a node, keysend to the attached pubkey.

**Comment by tobi-bams** [comment]
@soup20 I just pushed changes to the second-brain that enables users to make payments while they listen to podcasts or boost content.
The payment goes to the taggers and in circumstances where a tagger's public key is not provided the payment goes to sphinx nodes.
