### ISSUE TITLE
Light gray artifacts in scrollbar on Community tickets

### ISSUE THREAD

**Issue by rkirkendall** [stakwork/sphinx-relay#442]
What are these?

<img width="294" alt="Screen Shot 2022-09-30 at 4 48 32 PM" src="https://user-images.githubusercontent.com/1122859/193354006-2742593d-5dc4-4eab-905f-47430b9355bd.png">

**Comment by kevkevinpal** [comment]
resolved in this PR https://github.com/stakwork/sphinx-tribes/pull/295

also for the people page stuff you may want to post tickets in this repo instead
https://github.com/stakwork/sphinx-tribes

this repo is for the sphinx-relay backend connecting to the lightning node
