### ISSUE TITLE
git is missing in docker image causing errors

### ISSUE THREAD

**Issue by CalebFenton** [stakwork/sphinx-relay#447]
Relevant error is:

```
sphinx-relay    | [error] 10-14-22T13:14:27 [MISC] Error running a git command, probably not running in a git repository
sphinx-relay    | [error] 10-14-22T13:14:27 [MISC] { Error: Command failed: git describe --abbrev=0 --tags
sphinx-relay    | /bin/sh: 1: git: not found
```

Weird. Looks like it's installed: https://github.com/stakwork/sphinx-relay/blob/master/Dockerfile#L12 This file was updated last month and the `latest` tagged image came out 4 days ago, so it should be there.

I make sure I have the latest image:

```
$ docker pull sphinxlightning/sphinx-relay:latest
latest: Pulling from sphinxlightning/sphinx-relay
Digest: sha256:8dbf8848fbeab9d0577c0772d5512f25eb2396eb8b74fb4e7be255abff63cf34
Status: Image is up to date for sphinxlightning/sphinx-relay:latest
docker.io/sphinxlightning/sphinx-relay:latest
```

Start up bash and try to run `git` fails:

```
$ docker run --rm --entrypoint '' -it sphinxlightning/sphinx-relay:latest /bin/bash
node@c93ccba64277:/relay$ git
bash: git: command not found
```

My only thoughts are that I'm missing something completely or something went wrong uploading the latest image. Even the other Dockerfile is installing `git`: https://github.com/stakwork/sphinx-relay/blob/master/Dockerfile.lndrelay#L15

**Comment by Evanfeenstra** [comment]
@CalebFenton fixed in master

https://github.com/stakwork/sphinx-relay/commit/7e73752f04bbadb151f250f5d81566f1834f0fdd
