### ISSUE TITLE
Leaderboard: track earning and spending

### ISSUE THREAD

**Issue by soup20** [stakwork/sphinx-relay#457]
**Service involved**
Relay

**Goal:**
Track how many sats each user in a tribe has earned and spent in that tribe, which will be used as the data to create a leaderboard in that tribe.

**Method:**
- Track for sats earned: boost, direct payment
- Track for sats contributed: boost, direct payment, podcast feed stream payment
- "Activity" = sats earned + sats contributed (overall score to rank users on the leaderboard)

**Comment by kevkevinpal** [comment]
So for these changes, we had a conversation and decided that we'd want to store this data on relay either in a new table or preferably in one of the models that already exist. Then intermittently we can send the data over to the tribes server the user is connected to as a json blob or something

then the tribes server can display the information it gets and saves

**Comment by kevkevinpal** [comment]
we might want to make a new table in relay for this since it would make it cleaner

**Comment by Evanfeenstra** [comment]
The table we can use is the `ChatMemebers` table. That includes a record for each member of the tribe. So we can count up sats in new columns on that table

**Comment by tobi-bams** [comment]
@Evanfeenstra yeah the `ChatMembers` table would work, I suggest we create two new columns one that handles sats earned and another that handles sats contributed.

But also we could use a single column to handle both.

Please lemme know which you think would be better

**Comment by tobi-bams** [comment]
Also, I found this `totalSpent` column on the `ChatMember` table, please what is this suppose to be used for, as I could not trace it to where it is being used anywhere in the codebase

**Comment by Evanfeenstra** [comment]
@tobi-bams You are right, it is not used yet! So you can add a `totalEarned` also, and use 2 columns

**Comment by tobi-bams** [comment]
> @tobi-bams You are right, it is not used yet! So you can add a `totalEarned` also, and use 2 columns

Alright this work thanks!!
