### ISSUE TITLE
proxy endpoints

### ISSUE THREAD

**Issue by Evanfeenstra** [stakwork/sphinx-relay#463]
@tobi-bams 

We need 2 new endpoints for interacting with proxy

- add user. Create a new user in proxy (see the `utils/proxy.ts` file for how this is currently done. The function that it should run is `generateNewUser`). The endpoint should return the created user's pubkey and route_hint. 
- list users (return all Contacts with `isOwner=true`. but we also want to user's proxy balance in the returned object. So you can fetch the `adminURL + "balances"` to get a list of balances, and attach the correct balance to the correct Contact.

**Comment by kevkevinpal** [comment]
This should be completed and I see the endpoints here https://github.com/stakwork/sphinx-relay/blob/master/src/controllers/index.ts#L216

Evan let me know if we should reopen
