### ISSUE TITLE
Badges: Create badge bot

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-relay#479]
**Service involved:**
relay

**Goal:**
Build a bot that transfers a "Tribe Leader" badge to a user if they reach #1 on the tribe's leaderboard, if they have never been #1 before. We will prove we can do this with 1 badge, and add others when we are successful.

**Method:**

- look under ./src/builtin/...
- familiarize yourself with how to build a bot
- transfer asset will be used

**Comment by Evanfeenstra** [comment]
Here's some guidance @tobi-bams 

- look at WelcomeBot for inspiration
- make a new bot file called BadgeBot
- in builtin/index.ts you can add the BadgeBot.init() line with the other ones
- in the BadgeBot file, copy some WelcomeBot code
- in the `client.on(msg_types.MESSAGE...` part, you can do an action anytime there is a new message
- getOrCreate the ChatBot record for this tribe. Create default parameters as a JSON object that is stored in the "meta" field. Something like `[{badgeId: 123, rewardType: 'spent', amount: 100000}]`. Later on, this will be set by the admin via the app UI
- Every time a message comes in, check who its from
- check their ChatMember table to see their spent amount for example
- if that amount crosses the threshold of 100000 then award the badge
- and also create a text message like "Evan earned the Big Spender badge!" that is sent to the whole tribe (you can see how to create a message for the tribe in the WelcomeBot)

**Comment by tobi-bams** [comment]
@Evanfeenstra thanks.....

So I have done all from steps 1 - 5, but the issue I am having is, I am not able to intercept the message in the group

I have this
`client.on(msg_types.MESSAGE, async (message: Sphinx.Message) => {
    console.log(message)
  })`
  
  but each time I send a message to the tribe I am not able to see the log in my console

**Comment by Evanfeenstra** [comment]
@tobi-bams ok... its been a while since i worked on this, now i remember!

- add `badge` to the "builtinBots" array on builtin/mother.ts line 19
- then in your tribe you can write a text message like: `/bot install badge`, and the BadgeBot will be installed in your tribe. A ChatBot record will be created

**Comment by tobi-bams** [comment]
@Evanfeenstra
I did that already, but still can't intercept messages

Here is the details about the ChatBot installed already
` {
            "id": 7,
            "chatId": 48,
            "botUuid": null,
            "botType": 0,
            "botPrefix": "/badge",
            "botMakerPubkey": null,
            "botMakerRouteHint": null,
            "msgTypes": "[0]",
            "meta": null,
            "pricePerUse": 0,
            "createdAt": "2022-11-15T13:51:52.302Z",
            "updatedAt": "2022-11-15T13:51:52.302Z",
            "tenant": 1
        }`

**Comment by Evanfeenstra** [comment]
hmmmm maybe push a branch @tobi-bams and i can take a look at your code?

**Comment by tobi-bams** [comment]
@Evanfeenstra 

I just did that....
https://github.com/stakwork/sphinx-relay/tree/feat/badge-bot

**Comment by Evanfeenstra** [comment]
@tobi-bams when you did `/bot install badge` did you get a text response in the tribe? Your code looks good to me...

**Comment by tobi-bams** [comment]
@Evanfeenstra 

Yeah I got this......

`'<div style="position:relative;max-width:280px;min-width:180px;"><div style="font-size:15px;margin:5px 0;max-width:90%;">BadgeBot has been installed!</div></div>'`

**Comment by tobi-bams** [comment]
@Evanfeenstra 
Going through the codebase I found this line of code: https://github.com/stakwork/sphinx-relay/blob/master/src/network/intercept.ts#L98

I figured if it was a message the condition won't pass so added this line of code

`if (
              isMsgAndHasText ||
              isNotMsg ||
              botInTribe.botPrefix === '/badge'
            ) {
              didEmit = await emitMessageToBot(
                msg,
                botInTribe.dataValues,
                sender
              )
            }`

**Comment by Evanfeenstra** [comment]
@tobi-bams it should hit this line here https://github.com/stakwork/sphinx-relay/blob/master/src/network/intercept.ts#L137. so add some console logs to see why its not hitting this line

**Comment by Evanfeenstra** [comment]
> @Evanfeenstra Going through the codebase I found this line of code: https://github.com/stakwork/sphinx-relay/blob/master/src/network/intercept.ts#L98
> 
> I figured if it was a message the condition won't pass so added this line of code
> 
> `if ( isMsgAndHasText || isNotMsg || botInTribe.botPrefix === '/badge' ) { didEmit = await emitMessageToBot( msg, botInTribe.dataValues, sender ) }`

oh i see now! did that work? it looks good to me! The reason is that all the other bots only reply to messages that start with the botPrefix... but BadgeBot needs all messages

**Comment by tobi-bams** [comment]
> > @Evanfeenstra Going through the codebase I found this line of code: https://github.com/stakwork/sphinx-relay/blob/master/src/network/intercept.ts#L98
> > I figured if it was a message the condition won't pass so added this line of code
> > `if ( isMsgAndHasText || isNotMsg || botInTribe.botPrefix === '/badge' ) { didEmit = await emitMessageToBot( msg, botInTribe.dataValues, sender ) }`
> 
> oh i see now! did that work? it looks good to me! The reason is that all the other bots only reply to messages that start with the botPrefix... but BadgeBot needs all messages

Yes, this works
Yeah, and I also get the reason... Thanks!!!
