### ISSUE TITLE
Make all lsats passed a certain date invalid

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-relay#500]
We need all lsats passed a certain date to be marked invalid, and since the only application using the lsat functionality currently is the second brain project it seems like a reasonable changes.

We can set every lsat passed a specific unix timestamp as invalid.

We should also consider building a frontend UI where we can manually delete and manage lsats, incase someone else comes to this sort of issue in the future. Starting with the mac app since that is the only application able to do this stuff currently
https://github.com/stakwork/sphinx-mac/issues/22

**Comment by kevkevinpal** [comment]
@tobi-bams this is finished right? can you link the PR and close this?

**Comment by tobi-bams** [comment]
Yes, it is finished
