### ISSUE TITLE
Chat seen state not updated

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-relay#513]
When receiving a bot response message on a tribe you are admin of, the `chat.seen` attribute is not being updated to `false` and it should. 

On this line of the `receiveBotRes` method:

https://github.com/stakwork/sphinx-relay/blob/862e43ae6f479d2c8bf1811a9f5d863086fd736d/src/controllers/bots.ts#L456

we should do the same we do on `onReceive` on this line:

https://github.com/stakwork/sphinx-relay/blob/00b9794e1d7187380ca34ce235e9a7fafa39aba8/src/network/receive.ts#L115

**Comment by kevkevinpal** [comment]
so `chat.update({seen: false})` in an if block if there is no chat? @tomastiminskas

**Comment by tomastiminskas** [comment]
` if (chat) chat.update({ seen: false })`

That is the line that should be added before line 456. So if a chat exists, then we update it to seen: false. Let me know if it's clear
