### ISSUE TITLE
Add new tribe settings

### ISSUE THREAD

**Issue by soup20** [stakwork/sphinx-relay#533]
Work to be done in **Relay**.

## Context:
Building the structure for private company knowledge graphs.

## Goal:
Add the following settings as new columns in the tribes table in relay, so that the **tribe admin** can configure them from an interface in the app:
1. call recording on/off (will jitsi calls initiated from within this tribe automatically start recording, or not?)
2. S3 location (the address to which the recorded calls will be sent and stored in S3)
3. Jitsi server (identify the jitsi server that will be used for this tribe)
4. Stakwork API key (in order to send recorded audio to Stakwork for processing - make sure this key is secure)
5. Stakwork webhook (to be sent to stakwork along with audio file, so that Stakwork knows where to send response)

**Comment by tobi-bams** [comment]
@soup20 for the tribe admin to configure this am I to create a new endpoint, or I should update the create and update tribe endpoint to accommodate this??

**Comment by tobi-bams** [comment]
@soup20 Alright I guess that works, my concern was how do we handle it from the frontend(Desktop or mobile phone) side of this.

Would there be a dedicated screen to configuring call recording or this just happens as we create and edit tribe??

**Comment by tobi-bams** [comment]
@soup20 this answers my questions thanks

**Comment by tobi-bams** [comment]
Time estimation: 1 day at most, should be ready before the close of work today
