### ISSUE TITLE
Create tribe bot for call recordings

### ISSUE THREAD

**Issue by soup20** [stakwork/sphinx-relay#534]
Work to be done in **Relay**.

## Context:
Building the structure for private company knowledge graphs.

## Goal:
Create tribe bot which does the following:
1. detects the message that is sent when call is created from within tribe (when this message is sent, bot knows a call has started and is being recorded)
2. detects when there is an audio file that is ready to be processed (call is complete and has been stored in S3)
3. send audio file to Stakwork using stakwork endpoint and api key, and include a webhook for where to send response

## Details:
We'll need to build and use a data model for call recordings in relay, including the following:
- recording ID
- user who created the call?
- file name
- participants of the call?
- length of call?
- date/time of call
- status of call (new = created but no participants joined yet, in progress = at least 1 participant in the call, complete = all participants left the call, stored)
- webhook url for jarvis backend
- /call history

Link to project overview ticket: [https://github.com/stakwork/jarvis-backend/issues/83](url)

![Image](https://user-images.githubusercontent.com/104323003/212156848-837a033d-b01d-4ae1-be32-818c5c042768.png)

**Comment by tobi-bams** [comment]
@soup20 please where would the webhook URL come from and where should it be saved??? (I am thinking this would be saved in the tribe column also)

**Comment by tobi-bams** [comment]
> @tobi-bams Oh yeah it would be saved in the tribe column (I added it to the tribe settings ticket). So it would be entered in the tribe settings.

@soup20 thanks I just saw that

**Comment by tobi-bams** [comment]
@soup20 
Also in the model that's supposed to be created for call recording, is the recording ID just a number that is incremented or I would be getting the recordings ID from somewhere else, if the latter is the case what am I expecting? a number or a string

**Comment by tobi-bams** [comment]
Time estimation: 1 day at most 2 days but there might be some delays because I need the jitsi server and meme_server to be up and running so as to get the accurate flow and test properly.

**Comment by tobi-bams** [comment]
@soup20 the stakwork endpoint returns a project_id, should I add this to the call_recording table???

**Comment by tobi-bams** [comment]
@soup20 I do not understand what you mean here

**Comment by kevkevinpal** [comment]
> 

let me see if I can change this real quick
