### ISSUE TITLE
updateTotalMsgPerTribe crashes node

### ISSUE THREAD

**Issue by Evanfeenstra** [stakwork/sphinx-relay#546]
JS heap out of memory on that big query with multiple JOINS

@tobi-bams

**Comment by Evanfeenstra** [comment]
@tobi-bams please prioritize this one... with too many ChatMembers it crashes the node. Maybe it can be done in separate queires instead of a double JOIN?

**Comment by tobi-bams** [comment]
@Evanfeenstra, sure I would look into this next

**Comment by tobi-bams** [comment]
I would be working on this

**Comment by tobi-bams** [comment]
@Evanfeenstra, this is something I am proposing for now 

`try {
  const contacts = (await models.Contact.findAll({
    where: { isOwner: true },
  })) as ContactRecord[];
  for (let i = 0; i < contacts.length; i++) {
    const contact = contacts[i];
    const tribes = (await models.Chat.findAll({
      where: { ownerPubkey: contact.publicKey },
    })) as ChatRecord[];
    for (let j = 0; j < tribes.length; j++) {
      const tribe = tribes[j];
      const tribeMembers = (await models.ChatMember.findAll({
        where: { chatId: tribe.id },
      })) as ChatMemberRecord[];
      for (let k = 0; k < tribeMembers.length; k++) {
        const member = tribeMembers[k];
        const totalMessages = await models.Message.count({
          where: { sender: member.contactId, chatId: tribe.id },
        });
        console.log({
          tribe: tribe.id,
          alias: member.lastAlias,
          messages: totalMessages,
        });
      }
    }
  }
} catch (error) {
  console.log(error);
}`
