### ISSUE TITLE
Content feed status table and endpoints

### ISSUE THREAD

**Issue by soup20** [stakwork/sphinx-relay#549]
We will start syncing content feed status between devices so we need a new table on relay database and 2 endpoint to GET/POST records into it.

### Table

attributes with ? can be null. `feedID`, `feedURL` and `subscriptionStatus` are required

```
class ContentFeedStatus {
    var feedID: String
    var feedURL: String
    var subscriptionStatus:Bool
    var chatID:Int?
    var itemID: String?
    var episodesStatus: Json?
    var satsPerMinute: Int?
    var playerSpeed: Double?
}
```

### Endpoints

- **GET /content_feed_status**  to return all records on new table (add pagination with offset and limit)
- **POST /content_feed_status** to insert records: should receive array of objects, delete all the records on the table and insert the ones coming on the endpoint

**Comment by tomastiminskas** [comment]
@jimBeaux27 @pitoi while doing the refactor I realized we could want to persist and sync all episodes current time state (since with the new refactoring the current time of all episodes is being persisted and it's working great). Not just the last one played as assumed on this model. What do you think?

If you are agree, we could easily adapt it removing `playbackDuration` and `lastPlayedTime` from the table and adding a new `episodesState` attribute of type `json` which would persist an array with this structure:

```
[
    episode_id: {
        duration: Int,
        current_time: Int,
    },
    episode_id: {
        duration: Int,
        current_time: Int,
    }
]
```

We will keep the `itemID` since that will represent the last episode played

**Comment by pitoi** [comment]
@tomastiminskas and I discussed not re-downloading episode files when synching, we will store that episodes were downloaded just to have the data there.

**Comment by tomastiminskas** [comment]
Having the new `episodesStatus` attribute of type `JSON` will allow us to store duration and current-time of each episode plus any other information we want to start syncing like download state or whatever without having to change relay db structure.

**Comment by jimBeaux27** [comment]
I think @tomastiminskas logic makes sense but it's hard for me to make a call since there's a lot of history + other data models I'm less familiar with at play. I think the crux of the issue is we need some way to persist episode status in the cloud and on device correct?

**Comment by tomastiminskas** [comment]
@jimBeaux27 with the new refactor I'm doing we will be persisting episodes status on the device (using NSUserDefaults), so that part will be done. You will just need to get the info from there and make the call to relay at some specific moments. Actually most of them are variables on PodcastEpisode class that will get the info from UserDefaults when accessing the var. 
So `episode.duration` or `episode.currentTime` will always return the stored value to be sent to relay

I'm planning to have the refactor ready later today or tomorrow noon at most for you to help me testing and check the code.

**Comment by jimBeaux27** [comment]
Sounds good @tomastiminskas

**Comment by tobi-bams** [comment]
Here is the sample of the payload relay is expecting for the post endpoint
`{
    "contents": [
        {
            "feed_id": "string",
            "feed_url": "string",
            "subscription_status": true,
            "chat_id": 12,
            "item_id": "string",
            "episodes_status": [
                {
                    "episode_id": {
                        "duration": "Int",
                        "current_time": "Int"
                    }
                },
                {
                    "episode_id": {
                        "duration": "Int",
                        "current_time": "Int"
                    }
                }
            ],
            "sats_per_minute": 1234,
            "player_speed": 1.2
        },
        {
            "feed_id": "string",
            "feed_url": "string",
            "subscription_status": true,
            "chat_id": 12,
            "item_id": "string",
            "episodes_status": [
                {
                    "episode_id": {
                        "duration": "Int",
                        "current_time": "Int"
                    }
                },
                {
                    "episode_id": {
                        "duration": "Int",
                        "current_time": "Int"
                    }
                }
            ],
            "sats_per_minute": 1234,
            "player_speed": 1.2
        },
          {
            "feed_id": "string",
            "feed_url": "string",
            "subscription_status": true,
            "chat_id": 12,
            "item_id": "string",
            "episodes_status": [
                {
                    "episode_id": {
                        "duration": "Int",
                        "current_time": "Int"
                    }
                },
                {
                    "episode_id": {
                        "duration": "Int",
                        "current_time": "Int"
                    }
                }
            ],
            "sats_per_minute": 1234,
            "player_speed": 1.2
        }
    ]
}`

**Comment by tomastiminskas** [comment]
Endpoints 

```
post /content_feed_status
get /content_feed_status
```

**Comment by jimBeaux27** [comment]
Hey @tobi-bams I am taking a crack at this. So far I am getting a 400 error so I think there may be a couple issues. This is the payload I'm pushing up in the parameters right now:

```
{
  "content": [
    {
      "feed_id": "226249",
      "episode_status": [
        {
          "9677154949": {
            "current_time": 0,
            "duration": 0
          }
        },
        {
          "11758605084": {
            "current_time": 0,
            "duration": 0
          }
        },
        {
          "10040995773": {
            "duration": 0,
            "current_time": 0
          }
        },
        {
          "9717719413": {
            "duration": 0,
            "current_time": 0
          }
        },
        {
          "12565255995": {
            "duration": 0,
            "current_time": 0
          }
        },
        {
          "11299756810": {
            "current_time": 0,
            "duration": 0
          }
        },
        {
          "10151317489": {
            "duration": 0,
            "current_time": 0
          }
        },
        {
          "10966017751": {
            "duration": 0,
            "current_time": 0
          }
        },
        {
          "11472706252": {
            "duration": 0,
            "current_time": 0
          }
        },
        {
          "9813505424": {
            "duration": 0,
            "current_time": 0
          }
        },
        {
          "10689924554": {
            "duration": 0,
            "current_time": 0
          }
        },
        {
          "10548996796": {
            "current_time": 0,
            "duration": 0
          }
        },
        {
          "10713697247": {
            "duration": 0,
            "current_time": 0
          }
        },
        {
          "12071934321": {
            "current_time": 0,
            "duration": 0
          }
        },
        {
          "11421479363": {
            "duration": 0,
            "current_time": 0
          }
        },
        {
          "12663093570": {
            "duration": 0,
            "current_time": 0
          }
        },
        {
          "10945132781": {
            "duration": 0,
            "current_time": 0
          }
        },
        {
          "11816810001": {
            "duration": 0,
            "current_time": 0
          }
        },
        {
          "12022821823": {
            "duration": 0,
            "current_time": 0
          }
        },
        {
          "12139623972": {
            "current_time": 0,
            "duration": 0
          }
        },
        {
          "11675817614": {
            "current_time": 0,
            "duration": 0
          }
        },
        {
          "10787569271": {
            "current_time": 0,
            "duration": 0
          }
        },
        {
          "10530894012": {
            "duration": 0,
            "current_time": 0
          }
        },
        {
          "11085904744": {
            "duration": 0,
            "current_time": 0
          }
        },
        {
          "10890383807": {
            "current_time": 0,
            "duration": 0
          }
        },
        {
          "9534866007": {
            "duration": 0,
            "current_time": 0
          }
        },
        {
          "10668200927": {
            "current_time": 0,
            "duration": 0
          }
        },
        {
          "10262561594": {
            "duration": 0,
            "current_time": 0
          }
        },
        {
          "12802262979": {
            "current_time": 0,
            "duration": 3259
          }
        },
        {
          "10551927767": {
            "current_time": 0,
            "duration": 0
          }
        },
        {
          "9720879502": {
            "duration": 0,
            "current_time": 0
          }
        },
        {
          "11844873786": {
            "current_time": 0,
            "duration": 0
          }
        },
        {
          "10826914613": {
            "duration": 0,
            "current_time": 0
          }
        },
        {
          "12758163272": {
            "current_time": 0,
            "duration": 0
          }
        },
        {
          "11864285856": {
            "current_time": 0,
            "duration": 0
          }
        },
        {
          "9856757757": {
            "current_time": 0,
            "duration": 0
          }
        },
        {
          "10183181864": {
            "current_time": 0,
            "duration": 0
          }
        },
        {
          "12612681516": {
            "current_time": 0,
            "duration": 0
          }
        },
        {
          "11113879537": {
            "duration": 0,
            "current_time": 0
          }
        },
        {
          "10432830399": {
            "current_time": 0,
            "duration": 0
          }
        }
      ],
      "subscription_status": true,
      "feed_url": "https://anchor.fm/s/558f520/podcast/rss",
      "player_speed": 1
    }
  ]
}
```



Some differences I notice right off the bat:
1. I don't have a sats_per_minute field or chat_id field (sats_per_minute is actually dependent on the chat field). I think this should be optional so maybe it should not matter but I'll investigate further. Please let me know if the server would reject without this field.
2.  I don't seem to have an item_id field. I believe this is once again optional and dependent on a user listening to the "last podcast" available.

Could you let me know what fields exactly are mandatory? The spec seems to say that feed_url, feed_id, and subscription_status are the only ones. Could you confirm that is the case for the server?

or maybe it's an issue with the way I formatted or packaged data.

Please let me know if you have any theories or suggestions about what is awry.

Thanks,
Jim

**Comment by jimBeaux27** [comment]
Update after adjustments suggested by @tomastiminskas:
1. Changed content to contents for the key 
2. Ignore episode status if it's a 0

This was the result:

```
 "contents" : [
    {
      "episode_status" : [

      ],
      "feed_url" : "https:\/\/anchor.fm\/s\/558f520\/podcast\/rss",
      "subscription_status" : true,
      "feed_id" : "226249",
      "player_speed" : 1
    }
  ]
}
```

This time I get a 401 Unauthorized error. Back to the drawing board.

**Comment by jimBeaux27** [comment]
I was able to resolve the issue. I now get a 200 request. It is a timing issue where we don't authenticate if we're not yet connected

**Comment by tobi-bams** [comment]
@jimBeaux27 so sorry for the late reply, are we good now in regards to this????

Or do you still need some clarifications from me???

**Comment by tobi-bams** [comment]
also please, it's `"episodes_status"` and not `"episode_status"`

**Comment by tomastiminskas** [comment]
@tobi-bams could we add one more endpoint like a PUT that will just update the ContentFeedStatus based on a feedId? 

PUT
Params:
- "content" : JSON of the content feed status (as on the POST but just one, not an array)
- "feed_id" : the feed id to identify the record on the table to be updated

**Comment by tobi-bams** [comment]
Hi @tomastiminskas the update endpoint is available, here is the postman Documentation: https://sphinx-dev.postman.co/workspace/e4f736a7-6a90-4b58-8759-b62b397ad3a2/request/25494787-32fb8c05-cdfa-4bcd-b617-dab7208fb20b

**Comment by tomastiminskas** [comment]
@tobi-bams I don't have access to postman team. Could you give me please? My email is tomasalbertotiminskas@gmail.com

**Comment by tomastiminskas** [comment]
@tobi-bams 
Some changes needed on content feed Status endpoints:

1- In the PUT (updateContentFeedStatus) if the content doesn’t exist already, we should insert it
2- Create a GET by feed_id that will return just that specific contentFeedStatus

**Comment by tobi-bams** [comment]
@tomastiminskas,
I created a PR already, here is the postman Collection:

https://sphinx-dev.postman.co/workspace/Sphinx-APIs~e4f736a7-6a90-4b58-8759-b62b397ad3a2/request/25494787-01afd01b-e168-414c-b7fc-7207a5ffdb03
