### ISSUE TITLE
BOTS - silent messages

### ISSUE THREAD

**Issue by Evanfeenstra** [stakwork/sphinx-relay#559]
We need some bot messages to NOT show (only shown to tribe admin)

1. public
2. admin only (bot operator)
3. member only
4. member and admin

**Comment by Evanfeenstra** [comment]
for example, the `/call update ...` bot command should NOT be shown to the whole tribe!

**Comment by tobi-bams** [comment]
@Evanfeenstra, so this is what I came up with

1. Firstly, I add another check to this line, https://github.com/stakwork/sphinx-relay/blob/master/src/network/receive.ts#L137 to see if it's part of the command that an admin doesn't want to be broadcasted to the tribe
2. I add another column to the `ChatBot` table, this column specifies commands that the admin doesn't want to be broadcasted.
3. Add another command to enable admins to customize what bot commands they don't want to be broadcasted to the tribe (By default this command is added to the commands that admin don't want to be broadcasted to the whole tribe)

**Comment by tobi-bams** [comment]
Also, for the new column I specified earlier in number 2 above, should it be a new table or we could use Text and always parse to string before we add?

**Comment by Evanfeenstra** [comment]
That makes sense BUT how can you hide the responses from the hidden bot command? @tobi-bams

**Comment by Evanfeenstra** [comment]
Idea:
- add `only_owner` to the Action struct here https://github.com/stakwork/sphinx-relay/blob/master/src/controllers/botapi/index.ts#L33
- If the “action” has “only_owner: true” then skip the network.sendMessage here https://github.com/stakwork/sphinx-relay/blob/master/src/controllers/botapi/broadcast.ts#L70
- then we only need to figure out how to add the “only_owner” onto the action received from the bot lib

**Comment by tobi-bams** [comment]
I could get the onlyOwner in this line: https://github.com/stakwork/sphinx-bots/blob/master/src/client.ts#L137

I would also, update the MessageEmbed class: https://github.com/stakwork/sphinx-bots/blob/master/src/messageEmbed.ts#L10, to handle onlyOwner

@Evanfeenstra

**Comment by Evanfeenstra** [comment]
> > Idea:
> > 
> > * add `only_owner` to the Action struct here https://github.com/stakwork/sphinx-relay/blob/master/src/controllers/botapi/index.ts#L33
> > * If the “action” has “only_owner: true” then skip the network.sendMessage here https://github.com/stakwork/sphinx-relay/blob/master/src/controllers/botapi/broadcast.ts#L70
> > * then we only need to figure out how to add the “only_owner” onto the action received from the bot lib
> 
> Yea, this works...
> 
> Could we add the only_owner, with MessageEmbed object, so it could be this way `new Sphinx.MessageEmbed() .setAuthor('CallRecordingBot') .setDescription( 'Call Recording has been configured Successfully' ) .setOnlyOwner(Some logic that results to true or false) `

Yes!
- add `only_owner?` and `setOnlyOwner` here https://github.com/stakwork/sphinx-bots/blob/master/src/messageEmbed.ts#L10
- add `only_owner?` here https://github.com/stakwork/sphinx-bots/blob/master/src/client.ts#L251
- here, add the `only_owner` onto the `Action` https://github.com/stakwork/sphinx-bots/blob/master/src/client.ts#L134
```
if (m.embed && m.embed.only_owner) {
  a.only_owner = true
}
```
