### ISSUE TITLE
Limit number of calls shown in call history

### ISSUE THREAD

**Issue by soup20** [stakwork/sphinx-relay#563]
Work to be done on **Relay**.

Add a parameter to the /call history command for the number of calls that will be shown. We can have a default value of 10.

**Comment by kevkevinpal** [comment]
We can also expand on this in the future if we want by doing 

/call history {params to specify which calls}

**Comment by tobi-bams** [comment]
> We can also expand on this in the future if we want by doing
> 
> /call history {params to specify which calls}

Yea, I agree, but we would probably have to change the command.

for example `/call status ${call_id}`
