### ISSUE TITLE
Reprocess a call if not added to graph

### ISSUE THREAD

**Issue by soup20** [stakwork/sphinx-relay#564]
placeholder

**Comment by kevkevinpal** [comment]
We can create a loop such that after every n minutes we check the list of media in S3 against what we have in the callRecording table. If it exists in the S3 bucket but not the callRecording table go ahead and upload it

Question are we able to set that time in the bot and keep it within the bot code scope

based on the code is structured we'll need to make that upload bit a function we can use here aswell

**Comment by tobi-bams** [comment]
@kevkevinpal @soup20 it's not always easy to get the content of an s3 bucket through code, I would have to use aws sdk, also what if the bucket contains some content that is not to be processed by stakwork??

An alternative option I am thinking of is we loop through the call recording table, and find calls whose status is not `stores` then we hit the s3 bucket to check if we have that file, if we do have it, we send it to stakwork, if we don't we just leave it that way

**Comment by tobi-bams** [comment]
Also, in regards to how to set time for when we reprocess calls, I was thinking why not just send a command to the bot by the admin and the reprocessing steps mentioned above would be called into action.

@kevkevinpal @soup20

**Comment by tobi-bams** [comment]
@soup20 When a call recording is not successful the bot notifies the tribe

**Comment by kevkevinpal** [comment]
@tobi-bams that solution makes sense aswell? only question I have is that if the call is never recorded do we continue to check for it on the S3 bucket?

@soup20 yup we already get a response from stakwork when its a failure so we should be able to add that in

**Comment by tobi-bams** [comment]
@kevkevinpal that was why I mentioned that we should use a command to trigger call reprocessing instead of just asking the bot to do that itself in the background

So the admin types something like this: `/call retry`

**Comment by kevkevinpal** [comment]
> @kevkevinpal that was why I mentioned that we should use a command to trigger call reprocessing instead of just asking the bot to do that itself in the background
> 
> So the admin types something like this: `/call retry`

Ok this makes sense, I think this approach works then

**Comment by tobi-bams** [comment]
> * Use Stakwork project status endpoint to know if project fails on Stakwork
> * Add limit and timeout to call retry

@soup20 what should be the limit used here, I am thinking `10`

How many retries should we use, I am thinking `5`

**Comment by tobi-bams** [comment]
@soup20, when you say timeout what do you mean??

**Comment by gonzaloaune** [comment]
@tobi-bams here's the new endpoint and how to invoke it:

```bash
curl -k  -L -H 'Content-Type: application/json' -H 'Authorization: Token token="$YOUR_TOKEN"' 'https://jobs.stakwork.com/api/v1/projects/$PROJECT_ID/status'
```

**Comment by tobi-bams** [comment]
Thank you @gonzaloaune

**Comment by tobi-bams** [comment]
> @tobi-bams here's the new endpoint and how to invoke it:
> 
> ```shell
> curl -k  -L -H 'Content-Type: application/json' -H 'Authorization: Token token="$YOUR_TOKEN"' 'https://jobs.stakwork.com/api/v1/projects/$PROJECT_ID/status'
> ```

Here is the result I am getting: `{ success: true, data: { status: 'in_progress' } }`
Also are there other status I should be expecting??

**Comment by tobi-bams** [comment]
@gonzaloaune 
Please are there other status I should be expecting from the endpoint

I have `{ success: true, data: { status: 'in_progress' } }` and this `{ success: true, data: { status: 'completed' } }` for now
