### ISSUE TITLE
Tribe admin badge creation: read endpoint

### ISSUE THREAD

**Issue by soup20** [stakwork/sphinx-relay#575]
The app needs to know all badges that the admin has created and issued (transferred).

**Comment by kevkevinpal** [comment]
https://liquid.sphinx.chat/balances?pubkey=037820f6377ca9df93f15bad6968e5b06f9a87f1bc40c29e2ebeaeab06e0b5df62

`/balances?pubkey=<instert pubkey>`
This endpoint on the elements server should do the trick

**Comment by tobi-bams** [comment]
> https://liquid.sphinx.chat/balances?pubkey=037820f6377ca9df93f15bad6968e5b06f9a87f1bc40c29e2ebeaeab06e0b5df62
> 
> `/balances?pubkey=<instert pubkey>` This endpoint on the elements server should do the trick
> 
> This doesn't show exactly which one's you've created though just what you own and the tx's that happened You can figure out which ones you've created because they wouldn't be a tx in the tx's

Yes, I am filtering with the `badgeId` that I have stored on relay when a badge is created
