### ISSUE TITLE
MQTT root pubkey auth

### ISSUE THREAD

**Issue by Evanfeenstra** [stakwork/sphinx-relay#590]
If relay proxy root pubkey can auth with sphinx-mqtt and sphinx-auth as a "root pubkey" we can increase MQTT scalability a lot. In `mqtt-auth` we need to add ROOT_PUBKEYS (comma separated env var) that have ability to sub to any "pubkey" topic.

**Comment by Evanfeenstra** [comment]
What is the difference between `auth` route and `acl` route?

**Comment by Evanfeenstra** [comment]
Here is the lib that is used for MQTT github.com/fhmq/hmq/broker

**Comment by omoniyi24** [comment]
Thnanks @Evanfeenstra @kevkevinpal
