### ISSUE TITLE
Payments error handling

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-relay#643]
We need to wait until process finishes and return more descriptive error messages on failure for payment endpoints:
`- PUT /invoices`
`- POTS /payment`

**Comment by tomastiminskas** [comment]
This needs to be applied to all endpoints called from the app

**Comment by Evanfeenstra** [comment]
We can store FAILED payments of all kinds in the Messages table. 

So lets add an `error_message` column there, and we can store the reason that a payment failed in that column. Does that sound like a good solution @tomastiminskas ?

**Comment by Evanfeenstra** [comment]
There is an `error_message` column on Message now. Also, any routes that make payments return a error message string now

**Comment by tobi-bams** [comment]
@tomastiminskas `include_failures=true` is the params required to get failed payment on the GET `/payments` endpoint.
