### ISSUE TITLE
proto-loader-gen-types ($150 bounty in sats)

### ISSUE THREAD

**Issue by Evanfeenstra** [stakwork/sphinx-relay#662]
@antonilol Not sure how to run the awesome GRPC type definition script that you created. I added a couple new proto files for CLN support.

**Comment by antonilol** [comment]
the script can be run manually by running `./grpc_gen_types.sh` in the command line on (linux and probably mac os), currently it does not update the types after changing the proto files and the monthly run was broken because of npm, but this has been fixed in #663
