### ISSUE TITLE
Relay crashes

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-relay#673]
not sure why but I am seeing relay crash on version 2.3.0 and I'm being left with core.<pid> dump files but I'm not the best at reading them

**Comment by kevkevinpal** [comment]
@tobi-bams if you can take a look at this, I noticed the cluster 049 was running out of memory but you should see the core files in the containers

**Comment by Evanfeenstra** [comment]
No specific error message @kevkevinpal ? just a crash with the cluster out of memory?

**Comment by Evanfeenstra** [comment]
If its a recurring pattern, a good way to find the cause is to use "allocation sampling" in the Chrome devtools. I just pushed a start script that initiates relay with `--inspect` option, it might help

- `supervisorctl stop relay` 
- `npm run start-ecs-inspect --prefix /relay/`
- tunnel the inspect port from your local machine:
- ssh -i sphinx-instances.pem -L 9221:localhost:9229 ec2-user@3.238.22.25
- open `chrome://inspect`
- add a `localhost:9221` device
- Run "allocation sampling" for a long time period to see which functions are using the most memory

**Comment by kevkevinpal** [comment]
trying to do this but I'm getting an issue trying to connect
`channel 3: open failed: connect failed: Connection refused`

assuming its an issue reaching that port

**Comment by tobi-bams** [comment]
> trying to do this but I'm getting an issue trying to connect `channel 3: open failed: connect failed: Connection refused`
> 
> assuming its an issue reaching that port

Yea, I am also getting this error....

**Comment by kevkevinpal** [comment]
I think the issue might be if relay is having trouble connecting to lnd via grpc it eventually crashes

I think this is the case cause before 050 ran out of memory and lnd stopped working because something happened to neutrino so I had to delete these files and restart lnd
`rm .lnd/data/chain/bitcoin/mainnet/reg_filter_headers.bin .lnd/data/chain/bitcoin/mainnet/neutrino.db .lnd/data/chain/bitcoin/mainnet/block_headers.bin'`

but I only did that for one node. But after I did that for every node in the cluster we stopped getting the core files

I think something around here might be causing it
https://github.com/stakwork/sphinx-relay/blob/master/src/network/receive.ts#L484

**Comment by kevkevinpal** [comment]
Seeing this on one node
![Screen Shot 2023-05-03 at 4 18 27 PM](https://user-images.githubusercontent.com/15950706/236052123-6214a523-801d-4ac2-958f-fcf29bd4f505.png)

**Comment by kevkevinpal** [comment]
I'm observing its only happening for LND version v0.16.1

**Comment by Evanfeenstra** [comment]
> I'm observing its only happening for LND version v0.16.1

I wonder did anything change in the subscribeInvoices call?

**Comment by kevkevinpal** [comment]
> > I'm observing its only happening for LND version v0.16.1
> 
> I wonder did anything change in the subscribeInvoices call?

not sure but I noticed that our internal LND nodes are still at v0.15.4-beta but are not generating the core files like the other clusters

**Comment by kevkevinpal** [comment]
I also tried running relay locally against LND yesterday doing the allocation sampling and wasn't finding anything useful

**Comment by kevkevinpal** [comment]
This is the heap I got from running for an hour or so not exactly sure if this is helpful, I can try running again for the night and see if I get more obvious output
https://file.io/Xib4qmqok9Fv

**Comment by kevkevinpal** [comment]
testing to see if upgrading to lnd v0.16.2 helps with this issue

**Comment by Evanfeenstra** [comment]
> This is the heap I got from running for an hour or so not exactly sure if this is helpful, I can try running again for the night and see if I get more obvious output https://file.io/Xib4qmqok9Fv

after recording a heap allocation profile, you can see exactly which functions are using the most memory. It was super useful when i was trying to debug a memory overflow that ended up being due to one single function (the hub ping).

**Comment by Evanfeenstra** [comment]
> Looks like updating to LND v0.16.2 helped looks like the ec2 instance didn't run out of memory

awesome!

**Comment by kevkevinpal** [comment]
linking cause if we can get through this with no issues we can close this
https://github.com/stakwork/sphinx-relay/issues/688
