### ISSUE TITLE
Boost issue from user -> admin -> user

### ISSUE THREAD

**Issue by tobi-bams** [stakwork/sphinx-relay#679]
- when a user sends a boost in the tribe, sats are sent to the tribe admin first then the tribe admin forwards the sat to the user.
- We need to handle what happens when the user sends sats to the admin, but the admin is not able to forward the sats to the other user. 
- the sats should be sent back to the first user with the status of failed..

**Comment by Evanfeenstra** [comment]
Right. The `uuid` of the boost is the same throughout. So the sender can always check (if they receive a boost with an error_message), and update their original boost message with the error_message. And of course send a websocket message to the App with the failed boost details so the app can show it as failed

**Comment by Evanfeenstra** [comment]
@tomastiminskas This feature will send a websocket with type `boost` or `direct_payment` with an `error_message` if the boost fails (for example, if the original boost succeeds to the admin node, but then the forwarded boost fails). 

Is this the best logic for the websocket message? You will need to check if a `boost` is received with an `error_message` and update the boost in the UI to show that it failed. Or should we create separate websocket "type" for this for backward compatibility? Like `boost_failed`, `direct_payment_failed`?
