### ISSUE TITLE
Add /dist into .gitignore

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-relay#682]
We already have a git action to build and push to master after each push to master

https://github.com/stakwork/sphinx-relay/blob/master/.github/workflows/lint_format_and_build.yml

We might just need to modify this git action to force add something in the .gitignore but it would make our PR's not have a bunch of dist files in the diff

**Comment by Evanfeenstra** [comment]
keep in mind too that the Dockerfile doesn't even run `npm run build`, it uses the /dist from the repo itself

**Comment by kevkevinpal** [comment]
> keep in mind too that the Dockerfile doesn't even run `npm run build`, it uses the /dist from the repo itself

Yea I was thinking the gitaction could still build the files and commit them so they'll still be there just not when we create a PR

**Comment by kevkevinpal** [comment]
not sure what is best practice tho

**Comment by Evanfeenstra** [comment]
> not sure what is best practice tho

ya we are definitely not doing best practices. But its annoying for a newbie to have to understand typescript to clone and run relay. Which is why i made it this way

But if there is a way for the action to commit the files but not our PRs that would be nice...

**Comment by kevkevinpal** [comment]
The above PR should close this issue, lemme know what you think. Would make the PR's easier to read
