### ISSUE TITLE
Losing connection to tribes (Umbrel, raspi)

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-relay#691]
I am running sphinx-relay on a raspberry pi with an older version of umbrel (I manually update the docker images)

I'm connecting to it via tailscale/wireguard don't think this would cause any issues

I'm guessing either relay is not seeing the message via mqtt or not reading the incoming lighting message (cause I don't see the lightning bolt for conf)
I am able to message normally via dm's but for tribes this is happening, my only solution right now is to restart which solves the issue for a bit but then it happens again after some time.

I might add some logs around mqtt to see if something is going on there

**Comment by kevkevinpal** [comment]
Saw this error think it is related

<img width="1364" alt="Screenshot 2023-06-21 at 3 00 09 PM" src="https://github.com/stakwork/sphinx-relay/assets/15950706/bb0684c7-b2ec-42f5-93ea-2365cac5abe6">

**Comment by kevkevinpal** [comment]
@Evanfeenstra if this error happens does the connection to mqtt stop?

**Comment by kevkevinpal** [comment]
just broke again saw this log

```
[error] 06-22-23T15:02:23 [MISC] [hub error]: triggerNotification FetchError: request to https://hub.sphinx.chat/api/v1/nodes/notify failed, reason: getaddrinfo EAI_AGAIN hub.sphinx.chat
-> 2023-06-22 15:02:58: GET /balance 401 23ms
-> 2023-06-22 15:02:59: GET /app_versions 401 24ms
[info] 06-22-23T15:03:10 [TRIBES] CLOSE undefined
```

**Comment by Evanfeenstra** [comment]
https://github.com/stakwork/sphinx-relay/pull/714

**Comment by kevkevinpal** [comment]
if tests pass I'll create a docker image and test on my machine for a bit and then try and write unit tests for this so we can avoid it breaking again in the future

**Comment by kevkevinpal** [comment]
https://github.com/stakwork/sphinx-relay/pull/714 merged so I'm closing this issue, seems like a new release is out too!
