### ISSUE TITLE
Threading

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-relay#718]
New column on `Message` model:
- `thread_uuid: String? - Optional`
- Add `thread_uuid` to the message json returned to app on endpoints and socket
- Add `thread_uuid` param on sendMessage endpoint `POST /messages`
- `thread_uuid` should be sent on key send from sender relay to receiver relay (same than we do with `reply_uuid`)

**Comment by tomastiminskas** [comment]
We need the `POST /attachment` endpoint to also support `thread_uuid` param so we can send images/videos/audios in threads 

@kevkevinpal @Evanfeenstra

**Comment by kevkevinpal** [comment]
let me take a look at this @tomastiminskas

**Comment by kevkevinpal** [comment]
opened this PR but still want to add a test to insure we don't break this later
https://github.com/stakwork/sphinx-relay/pull/733

**Comment by kevkevinpal** [comment]
I think I can close this now @tomastiminskas lemme know if you still want this open
