### ISSUE TITLE
Endpoint for marking messages as read/unread

### ISSUE THREAD

**Issue by uncleJim21** [stakwork/sphinx-relay#774]
@Evanfeenstra @kevkevinpal we are responding to this request for ability to mark messages as read/unread to achieve parity with other similar apps: https://github.com/stakwork/sphinx-ios/issues/305. 

We have the app side database syncing but it occurred to us that we need to likewise sync up the relay with the changes as well. I'm thinking a simple PUT or PATCH http endpoint that just takes the message & chat UIDs would be sufficient.

Let me know your thoughts.

**Comment by tomastiminskas** [comment]
I would make the endpoint receives `chat_id` and array of `message_ids` to be set as `seen = false`. That way we can send the chat id and the last message id to be set as unseen as we are doing on the client side.

**Comment by uncleJim21** [comment]
On second thought the most effective way would be to have the following parameters:
chatID
shouldMarkUnread

if the flag is true it just marks the last message in the chat as unread.

If it’s false it marks all messages as read.

Those are the only two possible use cases for this endpoint.

the client shouldn’t have to process all the messageIds I think that’s over complicated.

**Comment by tomastiminskas** [comment]
@uncleJim21 we already have:

 `POST /messages/\(chatId)/read` 

so I would make a new one for unread:

 `POST /messages/\(chatId)/unread` 
 
 This new one would set chat and last message of the chat as `seen = false` (as you suggested)
 
 @kevkevinpal @Evanfeenstra could any of you take a look at this? So Jim can finish the feature. It should be a simple addition. And you can deploy to my nodes, so Jim can test on Tom Sim account

**Comment by uncleJim21** [comment]
@tomastiminskas I took a similar approach that just takes a flag and either calls the function you mentioned or it implements the mark as unread feature

**Comment by tomastiminskas** [comment]
@uncleJim21 that would work. Maybe let's Evan or Kev decide the best way to do it and inform us. I thought about a new one because the one we have for read can't be just replaced for the flag one since we need to keep it alive for old versions of the app using it

**Comment by uncleJim21** [comment]
@tomastiminskas agreed we need backward compatibility. I suppose your way is more consistent with the syntax. My code can refactor pretty easily to do it your way

**Comment by tomastiminskas** [comment]
@Evanfeenstra @kevkevinpal any updates on this? Thanks

**Comment by Evanfeenstra** [comment]
not sure why the push notification is sent, after that is removed we can merge
