### ISSUE TITLE
Sphinx invoice issues on creation

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-relay#784]
Andrew talked to the cashapp team. Our invoice doesn’t have a payment secret. 

I tried sending from pheonix, strike, cashapp and none of them can decode our lightning invoice.

**Comment by Evanfeenstra** [comment]
The fix was already in proxy, but prod proxy was on the wrong branch.

Please test again

**Comment by ecurrencyhodler** [comment]
Tested and its successful. We can close this issue!
