### ISSUE TITLE
Add `second_brain_url` to edit and create tribe endpoints

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-relay#804]
**Task**

Add `second_brain_url` to the following endpoints:

-  https://github.com/stakwork/sphinx-relay/blob/a3b3528a2cbe37b910fd72222dc6c2555df50014/src/controllers/chatTribes.ts#L398

-  https://github.com/stakwork/sphinx-relay/blob/a3b3528a2cbe37b910fd72222dc6c2555df50014/src/controllers/chats.ts#L268

- Need to support `second_brain_url`
- Edit or Create new tribe should be able to store `second_brain_url`

**Acceptance Criteria**

- [ ] Update the two endpoints to support `second_brain_url`

**Comment by Evanfeenstra** [comment]
why not use `app_url` here?

**Comment by tomsmith8** [comment]
We want to have a specific second brain icon in Tribes while still allowing a tribe admin to set a non secondbrain URL in Sphinx
